services:
  - type: worker
    name: noble-erp-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
